apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udacity-devops-capstone
  name: udacity-devops-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity-devops-capstone
  template:
    metadata:
      labels:
        app: udacity-devops-capstone
    spec:
      containers:
      - image: 420711152239.dkr.ecr.us-east-1.amazonaws.com/udacity-devops-capstone
        name: udacity-devops-capstone
