apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-devops-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
